name: eightWorkFlow
on: [push , workflow_dispatch]
jobs:
 buildJob:
  runs-on: ubuntu-latest
  steps:
    - name: Get Code
      uses: actions/checkout@v4
    - name: run code
      run: python greetings.py
    - uses: actions/upload-artifact@v4
      with:
        name: myArtifact
        path: greeting.txt
 deployJob:
   needs: buildJob
   runs-on: ubuntu-latest
   steps:
     - uses: actions/download-artifact@v4
       with:
         name: myArtifact
     - name: run code
       run: |
            ls -lrt
            cat greeting.txt
   
