name: MyFirstAction
on: workflow_dispactch 
jobs:
   MyFirstJob:
     runs-on: ubuntu-latest
     steps:      
      - name: Clone Repo
        run: echo "Clonning the repo"
      - name: Compile Repo
        run: echo "compiling buyer"
