name: fourth_workflow
on: push
jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: run code
        run: python greetingBoy.py
   
  secondJob: 
     needs: firstJob
     runs-on: ubuntu-latest
     steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: run code
        run: python greetingGirl.py
     
