name: second_workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: run code
        run: python3 -m unittest test_calculator.py
      - name: run tests
        run: python3 -m unittest test_calculator.py
