name: third_workflow
on: push
jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: run code
        run: python calculator.py add 5 3
      - name: run tests
        run: python3 -m unittest test_calculator.py
  secondJob: 
     runs-on: ubuntu-latest
     steps:
      - name: Get Code
        run: echo "getting the code"
      - name: run code
        run:  echo "running the code"
      - name: run tests
        run: echo "running the tests"
